export type Country = {
  name: string;
  callingCode: string;
  code: string;
};

export function getFlagUrl(code: string) {
  return `https://flagcdn.com/w40/${code}.png`;
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", callingCode: "+93", code: "af" },
  { name: "Åland Islands", callingCode: "+358", code: "ax" }, // Fixed: part of Finland
  { name: "Albania", callingCode: "+355", code: "al" },
  { name: "Algeria", callingCode: "+213", code: "dz" },
  { name: "American Samoa", callingCode: "+1684", code: "as" },
  { name: "Andorra", callingCode: "+376", code: "ad" },
  { name: "Angola", callingCode: "+244", code: "ao" },
  { name: "Anguilla", callingCode: "+1264", code: "ai" },
  { name: "Antigua and Barbuda", callingCode: "+1268", code: "ag" },
  { name: "Argentina", callingCode: "+54", code: "ar" },
  { name: "Armenia", callingCode: "+374", code: "am" },
  { name: "Aruba", callingCode: "+297", code: "aw" },
  { name: "Australia", callingCode: "+61", code: "au" },
  { name: "Austria", callingCode: "+43", code: "at" },
  { name: "Azerbaijan", callingCode: "+994", code: "az" },
  { name: "Bahamas", callingCode: "+1242", code: "bs" },
  { name: "Bahrain", callingCode: "+973", code: "bh" },
  { name: "Bangladesh", callingCode: "+880", code: "bd" },
  { name: "Barbados", callingCode: "+1246", code: "bb" },
  { name: "Belarus", callingCode: "+375", code: "by" },
  { name: "Belgium", callingCode: "+32", code: "be" },
  { name: "Belize", callingCode: "+501", code: "bz" },
  { name: "Benin", callingCode: "+229", code: "bj" },
  { name: "Bermuda", callingCode: "+1441", code: "bm" },
  { name: "Bhutan", callingCode: "+975", code: "bt" },
  { name: "Bolivia", callingCode: "+591", code: "bo" },
  { name: "Bosnia and Herzegovina", callingCode: "+387", code: "ba" },
  { name: "Botswana", callingCode: "+267", code: "bw" },
  { name: "Brazil", callingCode: "+55", code: "br" },
  { name: "British Indian Ocean Territory", callingCode: "+246", code: "io" },
  { name: "British Virgin Islands", callingCode: "+1284", code: "vg" },
  { name: "Brunei", callingCode: "+673", code: "bn" },
  { name: "Bulgaria", callingCode: "+359", code: "bg" },
  { name: "Burkina Faso", callingCode: "+226", code: "bf" },
  { name: "Burundi", callingCode: "+257", code: "bi" },
  { name: "Cambodia", callingCode: "+855", code: "kh" },
  { name: "Cameroon", callingCode: "+237", code: "cm" },
  { name: "Canada", callingCode: "+1", code: "ca" },
  { name: "Cape Verde", callingCode: "+238", code: "cv" },
  { name: "Caribbean Netherlands", callingCode: "+599", code: "bq" },
  { name: "Cayman Islands", callingCode: "+1345", code: "ky" },
  { name: "Central African Republic", callingCode: "+236", code: "cf" },
  { name: "Chad", callingCode: "+235", code: "td" },
  { name: "Chile", callingCode: "+56", code: "cl" },
  { name: "China", callingCode: "+86", code: "cn" },
  { name: "Christmas Island", callingCode: "+61", code: "cx" },
  { name: "Cocos (Keeling) Islands", callingCode: "+61", code: "cc" },
  { name: "Colombia", callingCode: "+57", code: "co" },
  { name: "Comoros", callingCode: "+269", code: "km" },
  { name: "Cook Islands", callingCode: "+682", code: "ck" },
  { name: "Costa Rica", callingCode: "+506", code: "cr" },
  { name: "Croatia", callingCode: "+385", code: "hr" },
  { name: "Cuba", callingCode: "+53", code: "cu" },
  { name: "Curaçao", callingCode: "+599", code: "cw" },
  { name: "Cyprus", callingCode: "+357", code: "cy" },
  { name: "Czechia", callingCode: "+420", code: "cz" },
  { name: "Denmark", callingCode: "+45", code: "dk" },
  { name: "Djibouti", callingCode: "+253", code: "dj" },
  { name: "Dominica", callingCode: "+1767", code: "dm" },
  { name: "Dominican Republic", callingCode: "+1809", code: "do" }, // Fixed: NANP +1809
  { name: "DR Congo", callingCode: "+243", code: "cd" },
  { name: "Ecuador", callingCode: "+593", code: "ec" },
  { name: "Egypt", callingCode: "+20", code: "eg" },
  { name: "El Salvador", callingCode: "+503", code: "sv" },
  { name: "Equatorial Guinea", callingCode: "+240", code: "gq" },
  { name: "Eritrea", callingCode: "+291", code: "er" },
  { name: "Estonia", callingCode: "+372", code: "ee" },
  { name: "Eswatini", callingCode: "+268", code: "sz" },
  { name: "Ethiopia", callingCode: "+251", code: "et" },
  { name: "Falkland Islands", callingCode: "+500", code: "fk" },
  { name: "Faroe Islands", callingCode: "+298", code: "fo" },
  { name: "Fiji", callingCode: "+679", code: "fj" },
  { name: "Finland", callingCode: "+358", code: "fi" },
  { name: "France", callingCode: "+33", code: "fr" },
  { name: "French Guiana", callingCode: "+594", code: "gf" },
  { name: "French Polynesia", callingCode: "+689", code: "pf" },
  { name: "French Southern and Antarctic Lands", callingCode: "+262", code: "tf" },
  { name: "Gabon", callingCode: "+241", code: "ga" },
  { name: "Gambia", callingCode: "+220", code: "gm" },
  { name: "Georgia", callingCode: "+995", code: "ge" },
  { name: "Germany", callingCode: "+49", code: "de" },
  { name: "Ghana", callingCode: "+233", code: "gh" },
  { name: "Gibraltar", callingCode: "+350", code: "gi" },
  { name: "Greece", callingCode: "+30", code: "gr" },
  { name: "Greenland", callingCode: "+299", code: "gl" },
  { name: "Grenada", callingCode: "+1473", code: "gd" },
  { name: "Guadeloupe", callingCode: "+590", code: "gp" },
  { name: "Guam", callingCode: "+1671", code: "gu" },
  { name: "Guatemala", callingCode: "+502", code: "gt" },
  { name: "Guernsey", callingCode: "+44", code: "gg" },
  { name: "Guinea", callingCode: "+224", code: "gn" },
  { name: "Guinea-Bissau", callingCode: "+245", code: "gw" },
  { name: "Guyana", callingCode: "+592", code: "gy" },
  { name: "Haiti", callingCode: "+509", code: "ht" },
  { name: "Honduras", callingCode: "+504", code: "hn" },
  { name: "Hong Kong", callingCode: "+852", code: "hk" },
  { name: "Hungary", callingCode: "+36", code: "hu" },
  { name: "Iceland", callingCode: "+354", code: "is" },
  { name: "India", callingCode: "+91", code: "in" },
  { name: "Indonesia", callingCode: "+62", code: "id" },
  { name: "Iran", callingCode: "+98", code: "ir" },
  { name: "Iraq", callingCode: "+964", code: "iq" },
  { name: "Ireland", callingCode: "+353", code: "ie" },
  { name: "Isle of Man", callingCode: "+44", code: "im" },
  { name: "Israel", callingCode: "+972", code: "il" },
  { name: "Italy", callingCode: "+39", code: "it" },
  { name: "Ivory Coast", callingCode: "+225", code: "ci" },
  { name: "Jamaica", callingCode: "+1876", code: "jm" }, // Fixed: NANP +1876
  { name: "Japan", callingCode: "+81", code: "jp" },
  { name: "Jersey", callingCode: "+44", code: "je" },
  { name: "Jordan", callingCode: "+962", code: "jo" },
  { name: "Kazakhstan", callingCode: "+7", code: "kz" },
  { name: "Kenya", callingCode: "+254", code: "ke" },
  { name: "Kiribati", callingCode: "+686", code: "ki" },
  { name: "Kosovo", callingCode: "+383", code: "xk" },
  { name: "Kuwait", callingCode: "+965", code: "kw" },
  { name: "Kyrgyzstan", callingCode: "+996", code: "kg" },
  { name: "Laos", callingCode: "+856", code: "la" },
  { name: "Latvia", callingCode: "+371", code: "lv" },
  { name: "Lebanon", callingCode: "+961", code: "lb" },
  { name: "Lesotho", callingCode: "+266", code: "ls" },
  { name: "Liberia", callingCode: "+231", code: "lr" },
  { name: "Libya", callingCode: "+218", code: "ly" },
  { name: "Liechtenstein", callingCode: "+423", code: "li" },
  { name: "Lithuania", callingCode: "+370", code: "lt" },
  { name: "Luxembourg", callingCode: "+352", code: "lu" },
  { name: "Macau", callingCode: "+853", code: "mo" },
  { name: "Madagascar", callingCode: "+261", code: "mg" },
  { name: "Malawi", callingCode: "+265", code: "mw" },
  { name: "Malaysia", callingCode: "+60", code: "my" },
  { name: "Maldives", callingCode: "+960", code: "mv" },
  { name: "Mali", callingCode: "+223", code: "ml" },
  { name: "Malta", callingCode: "+356", code: "mt" },
  { name: "Marshall Islands", callingCode: "+692", code: "mh" },
  { name: "Martinique", callingCode: "+596", code: "mq" },
  { name: "Mauritania", callingCode: "+222", code: "mr" },
  { name: "Mauritius", callingCode: "+230", code: "mu" },
  { name: "Mayotte", callingCode: "+262", code: "yt" },
  { name: "Mexico", callingCode: "+52", code: "mx" },
  { name: "Micronesia", callingCode: "+691", code: "fm" },
  { name: "Moldova", callingCode: "+373", code: "md" },
  { name: "Monaco", callingCode: "+377", code: "mc" },
  { name: "Mongolia", callingCode: "+976", code: "mn" },
  { name: "Montenegro", callingCode: "+382", code: "me" },
  { name: "Montserrat", callingCode: "+1664", code: "ms" },
  { name: "Morocco", callingCode: "+212", code: "ma" },
  { name: "Mozambique", callingCode: "+258", code: "mz" },
  { name: "Myanmar", callingCode: "+95", code: "mm" },
  { name: "Namibia", callingCode: "+264", code: "na" },
  { name: "Nauru", callingCode: "+674", code: "nr" },
  { name: "Nepal", callingCode: "+977", code: "np" },
  { name: "Netherlands", callingCode: "+31", code: "nl" },
  { name: "New Caledonia", callingCode: "+687", code: "nc" },
  { name: "New Zealand", callingCode: "+64", code: "nz" },
  { name: "Nicaragua", callingCode: "+505", code: "ni" },
  { name: "Niger", callingCode: "+227", code: "ne" },
  { name: "Nigeria", callingCode: "+234", code: "ng" },
  { name: "Niue", callingCode: "+683", code: "nu" },
  { name: "Norfolk Island", callingCode: "+672", code: "nf" },
  { name: "North Korea", callingCode: "+850", code: "kp" },
  { name: "North Macedonia", callingCode: "+389", code: "mk" },
  { name: "Northern Mariana Islands", callingCode: "+1670", code: "mp" },
  { name: "Norway", callingCode: "+47", code: "no" },
  { name: "Oman", callingCode: "+968", code: "om" },
  { name: "Pakistan", callingCode: "+92", code: "pk" },
  { name: "Palau", callingCode: "+680", code: "pw" },
  { name: "Palestine", callingCode: "+970", code: "ps" },
  { name: "Panama", callingCode: "+507", code: "pa" },
  { name: "Papua New Guinea", callingCode: "+675", code: "pg" },
  { name: "Paraguay", callingCode: "+595", code: "py" },
  { name: "Peru", callingCode: "+51", code: "pe" },
  { name: "Philippines", callingCode: "+63", code: "ph" },
  { name: "Pitcairn Islands", callingCode: "+64", code: "pn" },
  { name: "Poland", callingCode: "+48", code: "pl" },
  { name: "Portugal", callingCode: "+351", code: "pt" },
  { name: "Puerto Rico", callingCode: "+1787", code: "pr" }, // Fixed: NANP +1787
  { name: "Qatar", callingCode: "+974", code: "qa" },
  { name: "Republic of the Congo", callingCode: "+242", code: "cg" },
  { name: "Réunion", callingCode: "+262", code: "re" },
  { name: "Romania", callingCode: "+40", code: "ro" },
  { name: "Russia", callingCode: "+7", code: "ru" },
  { name: "Rwanda", callingCode: "+250", code: "rw" },
  { name: "Saint Barthélemy", callingCode: "+590", code: "bl" },
  { name: "Saint Helena, Ascension and Tristan da Cunha", callingCode: "+290", code: "sh" }, // Fixed: was +2
  { name: "Saint Kitts and Nevis", callingCode: "+1869", code: "kn" },
  { name: "Saint Lucia", callingCode: "+1758", code: "lc" },
  { name: "Saint Martin", callingCode: "+590", code: "mf" },
  { name: "Saint Pierre and Miquelon", callingCode: "+508", code: "pm" },
  { name: "Saint Vincent and the Grenadines", callingCode: "+1784", code: "vc" },
  { name: "Samoa", callingCode: "+685", code: "ws" },
  { name: "San Marino", callingCode: "+378", code: "sm" },
  { name: "São Tomé and Príncipe", callingCode: "+239", code: "st" },
  { name: "Saudi Arabia", callingCode: "+966", code: "sa" },
  { name: "Senegal", callingCode: "+221", code: "sn" },
  { name: "Serbia", callingCode: "+381", code: "rs" },
  { name: "Seychelles", callingCode: "+248", code: "sc" },
  { name: "Sierra Leone", callingCode: "+232", code: "sl" },
  { name: "Singapore", callingCode: "+65", code: "sg" },
  { name: "Sint Maarten", callingCode: "+1721", code: "sx" },
  { name: "Slovakia", callingCode: "+421", code: "sk" },
  { name: "Slovenia", callingCode: "+386", code: "si" },
  { name: "Solomon Islands", callingCode: "+677", code: "sb" },
  { name: "Somalia", callingCode: "+252", code: "so" },
  { name: "South Africa", callingCode: "+27", code: "za" },
  { name: "South Georgia", callingCode: "+500", code: "gs" },
  { name: "South Korea", callingCode: "+82", code: "kr" },
  { name: "South Sudan", callingCode: "+211", code: "ss" },
  { name: "Spain", callingCode: "+34", code: "es" },
  { name: "Sri Lanka", callingCode: "+94", code: "lk" },
  { name: "Sudan", callingCode: "+249", code: "sd" },
  { name: "Suriname", callingCode: "+597", code: "sr" },
  { name: "Svalbard and Jan Mayen", callingCode: "+47", code: "sj" },
  { name: "Sweden", callingCode: "+46", code: "se" },
  { name: "Switzerland", callingCode: "+41", code: "ch" },
  { name: "Syria", callingCode: "+963", code: "sy" },
  { name: "Taiwan", callingCode: "+886", code: "tw" },
  { name: "Tajikistan", callingCode: "+992", code: "tj" },
  { name: "Tanzania", callingCode: "+255", code: "tz" },
  { name: "Thailand", callingCode: "+66", code: "th" },
  { name: "Timor-Leste", callingCode: "+670", code: "tl" },
  { name: "Togo", callingCode: "+228", code: "tg" },
  { name: "Tokelau", callingCode: "+690", code: "tk" },
  { name: "Tonga", callingCode: "+676", code: "to" },
  { name: "Trinidad and Tobago", callingCode: "+1868", code: "tt" },
  { name: "Tunisia", callingCode: "+216", code: "tn" },
  { name: "Turkey", callingCode: "+90", code: "tr" },
  { name: "Turkmenistan", callingCode: "+993", code: "tm" },
  { name: "Turks and Caicos Islands", callingCode: "+1649", code: "tc" },
  { name: "Tuvalu", callingCode: "+688", code: "tv" },
  { name: "Uganda", callingCode: "+256", code: "ug" },
  { name: "Ukraine", callingCode: "+380", code: "ua" },
  { name: "United Arab Emirates", callingCode: "+971", code: "ae" },
  { name: "United Kingdom", callingCode: "+44", code: "gb" },
  { name: "United States", callingCode: "+1", code: "us" },
  { name: "United States Virgin Islands", callingCode: "+1340", code: "vi" },
  { name: "Uruguay", callingCode: "+598", code: "uy" },
  { name: "Uzbekistan", callingCode: "+998", code: "uz" },
  { name: "Vanuatu", callingCode: "+678", code: "vu" },
  { name: "Vatican City", callingCode: "+39", code: "va" },
  { name: "Venezuela", callingCode: "+58", code: "ve" },
  { name: "Vietnam", callingCode: "+84", code: "vn" },
  { name: "Wallis and Futuna", callingCode: "+681", code: "wf" },
  { name: "Western Sahara", callingCode: "+212", code: "eh" },
  { name: "Yemen", callingCode: "+967", code: "ye" },
  { name: "Zambia", callingCode: "+260", code: "zm" },
  { name: "Zimbabwe", callingCode: "+263", code: "zw" },
];